version: '3'

services:
  web_service:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=4000
      - CONFIG=dev_docker
    ports:
      - "4000:4000"
    restart: always
    volumes:
      - ..:/test_mast
    networks:
      - test_mast_net
#    command: ["sleep", "365d"]
    command: ["gunicorn", "main:app", "-c", "gunicorn_config.py"]
    depends_on:
      - db

  db:
    image: postgres96:9.6.test_mast
    build: ./pg
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    networks:
      - test_mast_net
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres

volumes:
    dbdata:


networks:
  test_mast_net:
    name: test_mast_net
    driver: bridge
