FROM python:3.9

ENV TZ=Europe/Moscow
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

WORKDIR /test_mast
ENV PYTHONPATH=/test_mast:${PYTHONPATH}

ADD ./requirements.txt /test_mast/requirements.txt
RUN pip install -r requirements.txt

WORKDIR /test_mast/web_service


